### PR TITLE
Updates eh?

### PR DESCRIPTION
**Pull request by Joshndroid**
Recent updates and some of your own updates that dont seem to be in your branch

### CODE REVIEW

**Comment by apascual89** [comment]
Since we decided to go unified, I removed the 3t branding I had added to stay as close to LOS as possible

**Comment by Joshndroid** [comment]
ill remove that commit and re-pull

**Comment by apascual89** [comment]
ok thanks

**Comment by Joshndroid** [comment]
there we go that commit should be gone now

**Comment by apascual89** [comment]
thanks just in time for an update!

**Pull request merged**
